<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Email - SMTP Configuration Test</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }
        .content {
            background: white;
            padding: 30px;
            border: 1px solid #e1e5e9;
            border-top: none;
        }
        .footer {
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            border-radius: 0 0 8px 8px;
            color: #6c757d;
            font-size: 14px;
        }
        .success-badge {
            background: #28a745;
            color: white;
            padding: 8px 16px;
            border-radius: 20px;
            display: inline-block;
            font-weight: bold;
            margin: 20px 0;
        }
        .sender-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            margin: 20px 0;
        }
        .sender-info strong {
            color: #495057;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>✅ SMTP Test Successful</h1>
        <p>Your sender configuration is working correctly!</p>
    </div>
    
    <div class="content">
        <div class="success-badge">
            🎉 Configuration Test Passed
        </div>
        
        <p><strong>Congratulations!</strong> If you're reading this email, it means your SMTP configuration is working perfectly.</p>
        
        <div class="sender-info">
            <h3>Sender Information:</h3>
            <p><strong>Name:</strong> {{ $sender->name }}</p>
            <p><strong>Email:</strong> {{ $sender->email }}</p>
            <p><strong>Domain:</strong> {{ $sender->domain->domain }}</p>
            @if($sender->domain->smtpConfig)
            <p><strong>SMTP Host:</strong> {{ $sender->domain->smtpConfig->host }}</p>
            <p><strong>SMTP Port:</strong> {{ $sender->domain->smtpConfig->port }}</p>
            @endif
        </div>
        
        <h3>What This Test Confirms:</h3>
        <ul>
            <li>✅ SMTP connection is successful</li>
            <li>✅ Authentication credentials are correct</li>
            <li>✅ Email delivery is functional</li>
            <li>✅ Sender reputation is good</li>
        </ul>
        
        <p><strong>Next Steps:</strong></p>
        <ol>
            <li>Your sender is now ready to send campaigns</li>
            <li>You can proceed with creating and sending email campaigns</li>
            <li>Monitor your email deliverability and engagement metrics</li>
        </ol>
    </div>
    
    <div class="footer">
        <p>This test email was sent at: {{ now()->format('F j, Y \a\t g:i A T') }}</p>
        <p>Generated by {{ config('app.name', 'Email Campaign System') }}</p>
    </div>
</body>
</html>
